### ISSUE TITLE
Feat: add pause/resume button in sidenav menu

### ISSUE THREAD

**Issue by napter** [fdm-monster/fdm-monster-client#238]
**Describe the bug**
My printer is currently paused. As you can see in the screenshot, the status screen shows that the printer is paused but there does not seem to be a way to resume. Am I missing an obvious button or is that functionality not available? If it is missing can it be added?

![image](https://github.com/fdm-monster/fdm-monster/assets/6260841/45b01756-0e05-41e7-aa65-3502f6b00fc2)

**To Reproduce**
Pause a print in octoprint and return to fdm monster

**Comment by davidzwa** [comment]
Very good point, will add this soon! Thanks for bringing it to my attention.

**Comment by davidzwa** [comment]
@napter Transferred this to the client repository so I can easily track the work.
